{
  parserClass="org.tianocore.edk2idea.Uni.UniParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Uni"
  psiImplClassSuffix="Impl"
  psiPackage="org.tianocore.edk2idea.Uni.psi"
  psiImplPackage="org.tianocore.edk2idea.Uni.psi.impl"

  elementTypeHolderClass="org.tianocore.edk2idea.Uni.psi.UniTypes"
  elementTypeClass="org.tianocore.edk2idea.Uni.psi.UniElementType"
  tokenTypeClass="org.tianocore.edk2idea.Uni.psi.UniTokenType"
  tokens=[
    SLASH
    EQUALS
    SHARP
    LANGDEF_KEYWORD
  ]
}

uniFile ::= header? (languageDefinition | stringEntry | property | COMMENT)*
header ::= SLASH EQUALS SHARP

languageDefinition ::= LANGDEF_KEYWORD languageName stringValues

stringEntry ::= STRING_KEYWORD stringName languageEntry*

stringName ::= WORD

languageEntry ::= LANGUAGE_KEYWORD languageName stringValues

languageName ::= WORD

stringValues ::= STRING_LITERAL+

property ::= (WORD | SHARP WORD?) (WORD | STRING_LITERAL)*
